podman run -d \
  --name ntp \
  --replace \
  --restart=always \
  --health-cmd "chronyc -n tracking || exit 1" \
  -e NTP_SERVERS="pool.ntp.org" \
  -e TZ="America/Chicago" \
  -v ntp-etc:/etc/chrony:Z \
  -v ntp-run:/run/chrony:Z \
  -v ntp-lib:/var/lib/chrony:Z \
  -p 123:123 \
  chrony:latest

#podman quadlet install ntp.container

#sudo systemctl enable --now podman-auto-update.timer
#sudo systemctl restart podman-auto-update.timer
